version: "3.9"

networks:
  default:
    name: ledger-network

services:
  messagingservice: # messaging service
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8080:8080

volumes:
  pgvolume: # declare a named volume to persist DB data